### ISSUE TITLE
Call to a member function getIP() on null

### ISSUE THREAD

**Issue by Shvquu** [BSchleyer/redhost-panel#23]
Guten Tag zusammen,

Ich habe heute das Red-Host Panel erneut versuch zu installieren, ich bekomme jedoch den Fehler oben genannt sobald ich mich einloggen will. Ich habe den composer installiert sowie auch die php version auf 7.4.33 gesetzt. Trotz dessen bekomme ich diesen Fehler.

Also ich weiß auch nicht warum, aber er findet die ip vom Nutzer nicht der sich einloggen will.

Hier auch nochmal den log von den Protokollen:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function getIP() on null in /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/app/functions/User.php:378\nStack trace:\n#0 /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/app/manager/customer/auth/login.php(61): User->logLogin()\n#1 /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/resources/auth/login.php(4): include('/var/www/vhosts...')\n#2 /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/router/app.php(19): include('/var/www/vhosts...')\n#3 /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/public/index.php(28): include_once('/var/www/vhosts...')\n#4 {main}\n thrown in /var/www/vhosts/hosthorizon.de/cp.hosthorizon.de/app/functions/User.php on line 378', referer: https://cp.hosthorizon.de/login

**Comment by bastianleicht** [comment]
Das Problem entsteht immer wenn du auf localhost die Webseite öffnest.

Dadurch das er dir auf localhost keine IP im Header zurückgeben kann, schlägt der Check hier fehl.

**Comment by bastianleicht** [comment]
Als fix müsstest du die Funktion ausklammern.

**Comment by Shvquu** [comment]
wie meinst du das, kannst du mir ein Beispiel nennen?

**Comment by Shvquu** [comment]
was auch das problem ist dann mit dem Session Token, er sagt mir beim login immer dann das die Session abgelaufen ist.

**Comment by Shvquu** [comment]
ich hab nun viel versucht, aber sobald ich das alles bei mir rausnehme bzw ausklammere mit // kommt die ganze Zeit das die Session abgelaufen sei und ich komme nicht ins dashboard

**Comment by bastianleicht** [comment]
Du musst da schon was zurückgeben. Sonst erstellt er keine Session in der Datenbank.

**Comment by Shvquu** [comment]
Und was soll ich da zurück geben, die ganze Sache ist ja nicht mal localhost sondern auf nem WebServer. Ne andere IP kann ich auch nicht nehmen, weil dann trz der gleiche Fehler kommt. Kannst du mir ggf dafür mal nen Beispiel code geben?

**Comment by BSchleyer** [comment]
Das Panel braucht eine IP-Adresse des Users der sich einloggt. Du kannst die Funktion und die Datenbank-Codes entfernen, dann wird diese nicht mehr gebraucht.

Andernfalls kannst Du den jeweiligen Code mit dd() als Funktion debuggen. Eventuelle Fehler können damit eventuell auffallen.

Ich teste das fix mal auf einem Webspace.

**Comment by BSchleyer** [comment]
Werde ich heute nicht mehr schaffen. Ich schreibe mir das nochmal für das Wochenende auf die Todo, andernfalls kann @bastianleicht das auch übernehmen und durchtesten - ggf. noch Änderungen machen.

Bin ab sofort im Urlaub.

**Comment by Shvquu** [comment]
Okay vielen Dank schonmal für die Hilfe

**Comment by jxelsw1337** [comment]
Hallo hab hier einen finalen Fix für das Problem:

geht in  ```functions\User.php``` und ersetzt die logLogin  Funktion:

>     public function logLogin($user_id, $user_addr, $user_agent)
>     {
>         if(is_null($user_addr)) {
>             $user_addr = '127.0.0.1';
>         } else {
>             $user_addr = $user->getIP();
>         }
> 
>         $SQL = self::db()->prepare("INSERT INTO `login_logs`(`user_id`, `user_addr`, `user_agent`) VALUES (?,?,?)");
>         $SQL->execute(array($user_id, $user_addr, $user_agent));
>     }

zu das:

>     public function logLogin($user_id, $user_addr, $user_agent)
>     {
>         $SQL = self::db()->prepare("INSERT INTO `login_logs`(`user_id`, `user_addr`, `user_agent`) VALUES (?,?,?)");
>         $SQL->execute(array($user_id, $user_addr, $user_agent));
>     }

Dann geht ihr zu ```controller\PageController.php```

Und ersetzt 

>     if(is_null($user_addr)){
>         $ip = $user->getIP();
> 
>         if(is_null($ip)) {
>             $user_addr = '127.0.0.1';
>         } else {
>             $user_addr = $user->getIP();
>         }
> 
>         $SQL = $db->prepare("UPDATE `users` SET `user_addr` = :user_addr WHERE `id` = :id");
>         $SQL->execute(array(":user_addr" => $user_addr, ":id" => $userid));
>     }

zu

>     if (is_null($user_addr)) {
>         $SQL = $db->prepare("UPDATE `users` SET `user_addr` = :user_addr WHERE `id` = :id");
>         $SQL->execute(array(":user_addr" => $user->getIP(), ":id" => $userid));
>         $user_addr = $user->getIP();
>     }

Als nächstes ersetzt ihr die diese IF Abfrage:

>     if('127.0.0.1' != $user_addr){
>         if(isset($_COOKIE['old_session_token'])){
>             if($user->isInTeam($_COOKIE['old_session_token'])){
> 
>             } else {
>                 $_SESSION['info_msg'] = 'Session Expired';
>                 setcookie('session_token', null, time(), '/'); header('Location: '.$helper->url().'login');
>                 die();
>             }
>         } else {
>             $_SESSION['info_msg'] = 'Session Expired';
>             setcookie('session_token', null, time(), '/'); header('Location: '.$helper->url().'login');
>             die();
>         }
>     }

zu:

> 
>     if($user->getIP() != $user_addr) {
>         if(isset($_COOKIE['old_session_token'])){
>             if($user->isInTeam($_COOKIE['old_session_token'])){
> 
>             } else {
>                 $_SESSION['info_msg'] = 'Deine Session ist abgelaufen. Bitte logge dich erneut ein';
>                 setcookie('session_token', null, time(), '/'); header('Location: '.$helper->url().'login');
>                 die();
>             }
>         } else {
>             $_SESSION['info_msg'] = 'Deine Session ist abgelaufen. Bitte logge dich erneut ein';
>             setcookie('session_token', null, time(), '/'); header('Location: '.$helper->url().'login');
>             die();
>         }
>    

Nach diesen Änderungen sollte der Login wieder funktionieren :)

**Comment by Shvquu** [comment]
Danke für deine Hilfe, ich glaube damit ist das problem auch erstmal gelöst
